In [2]:
import numpy as np


arr = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]) # numpy array 
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [9]:
arr.shape
# arr[r,c]
print(arr[1,2])
arr[1,2:5:2]

10


array([10, 12])

In [15]:
















# shape of the array 
arr.shape

# get specific element by [r,c]
print(arr[1,2])

# get a specific row 

arr[1,:]

# get a specific column 
arr[:,3]

# get a little more fancy.
arr[0,7::-2]

10


array([7, 5, 3, 1])